@BASE_URL = http://localhost:3001

# get all persons
GET {{BASE_URL}}/api/persons HTTP/1.1

###

# get person with unknown ID (Example: 5)

GET {{BASE_URL}}/api/persons/5 HTTP/1.1

###

# get person with known ID (Example: 1)

GET {{BASE_URL}}/api/persons/1 HTTP/1.1

###

# delete person given ID 

DELETE {{BASE_URL}}/api/persons/4 HTTP/1.1

###

# add new person

POST {{BASE_URL}}/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "CyberFrost",
  "number": "39-44-5323530"
}

###

# add new person invalid request ( with missing required data)

POST {{BASE_URL}}/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "CyberFrost",
  "age": 20
}

###

# add new person ( with adding not needed data)

POST {{BASE_URL}}/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "CyberFrost1",
  "number": "39-44-5323531", 
  "age": 20
}